general:
  debug-level: 0
  update-check: true
  language: en_US
check:
  death-time: true
  online-time: true
afk:
  enabled: true
  interval: 60
  timeout: 900
events:
  enabled: true
  interval: 10
data:
  manager: 'flatfile'
managers:
  mysql:
    host: localhost
    port: '3306'
    database: minecraft
    username: root
    password: password